### ISSUE TITLE
Make album art selection algorithm match Google's Music Manager

### ISSUE THREAD

**Issue by nelsonjr** [thebigmunch/google-music-proto#9]
Upload of MP3 files that have embedded album art is not being picked up by Google Music.

## Expected
Uploading a music file to have the album created with the cover art

## Actual
Album is created with no cover art

**Comment by thebigmunch** [comment]
For the record, I just uploaded an MP3 with a front cover successfully. So, I'd double down on thinking the picture isn't set as the front cover in the file(s).

**Comment by nelsonjr** [comment]
Not sure. How do I check it? When I upload the mp3 using Google Music extension the picture shows up okay. Also if we inspect the audio_metadata.Format we can see an ID3v2Picture on it:
```
<MP3 ({
    'filepath': 'Mega Mix 75 - 01 Misteriosa - Merengue.mp3',
    'filesize': '4.63 MiB',
    'pictures': [
        <ID3v2Picture ({
            'data': '78.06 KiB',
            'description': '',
            'height': 600,
            'mime_type': 'image/jpeg',
            'type': <ID3PictureType.OTHER>,
            'width': 600,
        })>,
    ],
    'streaminfo': <MP3StreamInfo ({
        'bitrate': '165 Kbps',
        'bitrate_mode': <MP3BitrateMode.VBR>,
        'channel_mode': <MP3ChannelMode.JOINT_STEREO>,
        'channels': 2,
        'duration': '03:51',
        'layer': 3,
        'protected': False,
        'sample_rate': '44.1 KHz',
        'version': 1,
    })>,
    'tags': <ID3v2Frames ({
        'album': ['Mega Mix 75'],
        'albumartist': ['Zumba®'],
        'artist': ['Max Pizzolante'],
        'bpm': ['147'],
        'date': ['2020'],
        'genre': ['Merengue'],
        'title': ['Misteriosa - Merengue'],
        'tracknumber': ['1'],
    })>,
})>
```
That's where I got the overridden image from to begin with.

**Comment by thebigmunch** [comment]
> Not sure. How do I check it?

You can see the type in the ID3v2Picture object: ``'type': <ID3PictureType.OTHER>``.

So, after some testing, it seems Google's Music Manager uses this selection method for album art:

* If picture(s) of type 'front cover' are found, use the first one of those in the list.
* If picture(s) of type 'other' are found, use the first one of those in the list.
* If picture(s) of type 'back cover' are found, use the first one of those in the list.

So, I'll change the ``get_album_art`` function to match that algorithm.

**Comment by thebigmunch** [comment]
So, I'll probably make a release later today. Until then, you can get the new album art selection algorithm with: ``pip install -U git+https://github.com/thebigmunch/google-music-proto``.
